### ISSUE TITLE
Exception encountered when processing CAS04 w.r.t. NVR11 with extra decimation level

### ISSUE THREAD

**Issue by kkappler** [simpeg/aurora#196]
The script  `02b_process_cas04_mth5.py` was processing CAS04 w.r.t. NVR11 and got this:

> Window is longer than the time series
Traceback (most recent call last):
  File "02b_process_cas04_mth5.py", line 316, in <module>
    main()
  File "02b_process_cas04_mth5.py", line 291, in main
    process_with_remote("CAS04", "NVR11")
  File "02b_process_cas04_mth5.py", line 281, in process_with_remote
    return_collection=False,
  File "/home/kkappler/software/irismt/aurora/aurora/pipelines/process_mth5.py", line 402, in process_mth5
    processing_config, i_dec_level, run_obj, run_xrts, units, row.station_id
  File "/home/kkappler/software/irismt/aurora/aurora/pipelines/process_mth5.py", line 141, in make_stft_objects
    stft_obj = run_ts_to_stft(stft_config, run_xrts)
  File "/home/kkappler/software/irismt/aurora/aurora/pipelines/time_series_helpers.py", line 209, in run_ts_to_stft
    run_xrts, dt=1.0 / decimation_obj.decimation.sample_rate
  File "/home/kkappler/software/irismt/aurora/aurora/time_series/windowing_scheme.py", line 187, in apply_sliding_window
    return_xarray=True,
  File "/home/kkappler/software/irismt/aurora/aurora/time_series/windowing_scheme.py", line 223, in _apply_sliding_window_numpy
    data, self.num_samples_window, self.num_samples_advance
  File "/home/kkappler/software/irismt/aurora/aurora/time_series/window_helpers.py", line 66, in sliding_window_crude
    len(data), num_samples_window, num_samples_advance
  File "/home/kkappler/software/irismt/aurora/aurora/time_series/window_helpers.py", line 35, in available_number_of_windows_in_array
    raise Exception
Exception

**Comment by kkappler** [comment]
This was not related to coherence sorting but instead it occurred when I changed the band setup file 
from `BANDS_DEFAULT_FILE` to `band_setup_emtf_nims.txt`.

This maybe related to issue #182

**Comment by kkappler** [comment]
This is fixed with processing precheck (#182 )
